import { existsSync, writeFileSync } from "node:fs";
import { join as pathJoin } from "node:path";
import { homedir } from "node:os";
import { ui } from "../ui.js";
import {
  loadIdentityFromFile,
  loadIdentityFromHex,
  generateIdentity,
  pubkeyToHex,
  createRuntime,
} from "@swati/core";
import { LocalFileStorage, LocalGate } from "@swati/core/adapters";

export interface JoinOptions {
  target: string;
  role: string;

  identityFile?: string;

  axlEndpoint?: string;

  walletKey?: string;
  network?: string;
  rpcUrl?: string;
  contractAddress?: string;

  once?: boolean;

  config?: string;

  input?: string;
}

export async function runJoin(opts: JoinOptions): Promise<void> {
  const isOnchain = opts.target.startsWith("0x") && opts.target.length === 66;

  const spinner = ui.spinner("Loading choreography…");
  spinner.start();

  let choreoId: string | undefined;
  let sourceTs: string | undefined;
  let manifestUri: string | undefined;
  let choreoRoles: string[] = [];

  if (isOnchain) {
    if (!opts.walletKey) {
      spinner.fail("--wallet-key is required for on-chain choreoId");
      ui.dim("  swati join 0x<choreoId> --role <role> --wallet-key $WALLET_KEY");
      process.exit(1);
    }

    const { OnchainRegistry } = await import("@swati/registry-onchain");
    const network = toNetwork(opts.network);
    const registry = new OnchainRegistry({
      network,
      walletPrivateKey: opts.walletKey,
      ...(opts.rpcUrl ? { rpcUrl: opts.rpcUrl } : {}),
      ...(opts.contractAddress ? { contractAddress: opts.contractAddress as `0x${string}` } : {}),
    });

    const info = await registry.getChoreography(opts.target).catch(() => null);
    if (!info) {
      spinner.fail(`Choreography ${opts.target} not found on-chain`);
      process.exit(1);
    }

    choreoId = opts.target;
    manifestUri = info.manifestUri;
    choreoRoles = info.roles;
    spinner.text = `Found "${info.name}" [${info.roles.join(", ")}]`;

    if (info.sourceUri) {
      try {
        sourceTs = await fetchText(info.sourceUri);
      } catch {}
    }
  } else {
    manifestUri = opts.target;
    spinner.text = "Using manifest URI";
  }

  spinner.text = "Loading identity…";
  let identity;
  let identityFilePath = opts.identityFile;

  if (identityFilePath) {
    identity = await loadIdentityFromFile(identityFilePath);
  } else if (process.env["SWATI_PRIVKEY_HEX"]) {
    identity = await loadIdentityFromHex(process.env["SWATI_PRIVKEY_HEX"], opts.role);
  } else {
    const defaultPath = pathJoin(homedir(), ".swati", `${opts.role}.key.json`);
    if (existsSync(defaultPath)) {
      identity = await loadIdentityFromFile(defaultPath);
      identityFilePath = defaultPath;
      spinner.text = `Identity loaded from ${defaultPath}`;
    } else {
      identity = await generateIdentity(opts.role);
      const keyJson = JSON.stringify(
        {
          name: opts.role,
          pubkey: pubkeyToHex(identity.pubkey),
          privateKey: Buffer.from(identity.privateKey).toString("hex"),
          note: "Auto-generated by swati join. Keep this file secret.",
        },
        null,
        2,
      );
      writeFileSync(defaultPath, keyJson, { mode: 0o600 });
      identityFilePath = defaultPath;
      spinner.text = `New identity saved to ${defaultPath}`;
    }
  }

  const pubkeyHex = pubkeyToHex(identity.pubkey);

  let axlPeerId = "";
  const axlEndpoint = opts.axlEndpoint ?? process.env["AXL_ENDPOINT"] ?? "http://localhost:9002";

  try {
    const regMod = (await import("@swati/registry-onchain")) as any;
    axlPeerId = await regMod.getAxlPeerIdFromTopology(axlEndpoint);
    spinner.text = `AXL peer: ${axlPeerId.slice(0, 12)}…`;
  } catch {
    spinner.warn("AXL node not reachable at " + axlEndpoint + " — proceeding without axlPeerId");
  }

  if (isOnchain && opts.walletKey && choreoId) {
    spinner.text = "Registering on-chain…";
    try {
      const { OnchainRegistry } = await import("@swati/registry-onchain");
      const network = toNetwork(opts.network);
      const registry = new OnchainRegistry({
        network,
        walletPrivateKey: opts.walletKey,
        ...(opts.rpcUrl ? { rpcUrl: opts.rpcUrl } : {}),
        ...(opts.contractAddress ? { contractAddress: opts.contractAddress as `0x${string}` } : {}),
      });

      const reg = registry as any;
      const existing = await reg.getRole(choreoId, opts.role).catch(() => null);
      if (existing?.pubkeyHex === pubkeyHex) {
        if (axlPeerId && existing.axlPeerId !== axlPeerId) {
          await reg.updateAxlPeerId(choreoId, opts.role, axlPeerId);
          spinner.text = "AXL peer ID updated on-chain";
        } else {
          spinner.text = "Already registered, skipping";
        }
      } else {
        await reg.claimRole(choreoId, opts.role, pubkeyHex, axlPeerId);
        spinner.text = "Role claimed on-chain";
      }
    } catch (cause: unknown) {
      const msg = String(cause);
      if (msg.includes("NotGranted")) {
        spinner.fail(`Role "${opts.role}" is not open and not granted to your wallet.`);
        ui.warn("Ask the choreography publisher to run:");
        ui.dim(
          `  swati registry grant-role --choreo-id ${choreoId} --role ${opts.role} --grantee <your-wallet> --wallet-key $PUBLISHER_KEY`,
        );
        process.exit(1);
      }
      spinner.warn(`On-chain registration failed (${msg.slice(0, 80)}) — continuing in local mode`);
    }
  }

  spinner.succeed(`Ready as "${opts.role}"${choreoId ? ` in ${choreoId.slice(0, 14)}…` : ""}`);

  let localScorePath: string | undefined;
  if (sourceTs) {
    const fname = `${opts.role}-choreo.ts`;
    writeFileSync(fname, sourceTs, "utf-8");
    localScorePath = fname;
    ui.dim(`  Source saved: ${fname}`);
  }

  if (opts.once || !isOnchain) {
    await runOnce(opts, identity, identityFilePath, axlEndpoint, localScorePath, manifestUri);
    return;
  }

  await runDaemon(
    opts,
    identity,
    identityFilePath,
    axlEndpoint,
    choreoId!,
    choreoRoles,
    localScorePath,
  );
}

async function runOnce(
  opts: JoinOptions,
  identity: Awaited<ReturnType<typeof generateIdentity>>,
  identityFilePath: string | undefined,
  axlEndpoint: string,
  localScorePath?: string,
  manifestUri?: string,
): Promise<void> {
  const { runRun } = await import("./run.js");
  const runArgs: Record<string, unknown> = { role: opts.role };
  if (localScorePath) runArgs["score"] = localScorePath;
  if (!localScorePath && manifestUri) runArgs["id"] = manifestUri;
  if (opts.config) runArgs["config"] = opts.config;
  if (opts.input) runArgs["input"] = opts.input;
  if (identityFilePath) runArgs["identityFile"] = identityFilePath;
  await runRun(runArgs as unknown as Parameters<typeof runRun>[0]);
}

async function runDaemon(
  opts: JoinOptions,
  identity: Awaited<ReturnType<typeof generateIdentity>>,
  identityFilePath: string | undefined,
  axlEndpoint: string,
  choreoId: string,
  _roles: string[],
  localScorePath?: string,
): Promise<void> {
  let OnchainTrigger: any;
  try {
    const mod = await (
      Function("m", "return import(m)") as (m: string) => Promise<Record<string, unknown>>
    )("@swati/trigger-onchain");
    OnchainTrigger = mod["OnchainTrigger"];
  } catch {
    ui.warn("@swati/trigger-onchain not available — falling back to one-shot mode");
    await runOnce(opts, identity, identityFilePath, axlEndpoint, localScorePath, choreoId);
    return;
  }

  const { loadConfig } = await import("../config-loader.js");
  const cfg = opts.config
    ? await loadConfig(opts.config)
    : await loadConfig().catch(() => buildDefaultConfig(axlEndpoint, opts));

  const resolverMod = await (Function("m", "return import(m)") as (m: string) => Promise<any>)(
    "@swati/resolver-onchain",
  ).catch(() => ({}));

  const OnChainRegistryResolver: any = resolverMod["OnChainRegistryResolver"] ?? null;
  const { OnchainRegistry } = await import("@swati/registry-onchain");
  const network = toNetwork(opts.network);

  const regCfg: Record<string, unknown> = { network };
  if (opts.walletKey) regCfg["walletPrivateKey"] = opts.walletKey;
  if (opts.rpcUrl) regCfg["rpcUrl"] = opts.rpcUrl;
  if (opts.contractAddress) regCfg["contractAddress"] = opts.contractAddress;

  const registry = new OnchainRegistry(regCfg as any);

  const resolver = OnChainRegistryResolver
    ? new OnChainRegistryResolver({ choreoId, registry })
    : cfg.resolver;

  let transport = cfg.transport;
  if (!transport) {
    const axlMod = await (
      Function("m", "return import(m)") as (m: string) => Promise<Record<string, unknown>>
    )("@swati/transport-axl");

    const WireChannel = axlMod["WireChannel"] as any;
    transport = new WireChannel({ endpoint: axlEndpoint });
  }

  const runtime = createRuntime({
    transport,
    resolver,
    storage: cfg.storage,
    gates: cfg.gates,
    llm: cfg.llm,
  });
  await runtime.start();

  const trigger = new OnchainTrigger(regCfg);

  ui.ok(`Daemon started — role "${opts.role}" listening for runs on ${choreoId.slice(0, 14)}…`);
  ui.dim("  Waiting for RunRequested events. Press Ctrl+C to stop.");
  ui.dim(`  Trigger runs with: requestRun({ choreoId: "${choreoId}", input: {...} })`);

  let choreo;
  if (localScorePath) {
    const { pathToFileURL } = await import("node:url");
    const { resolve } = await import("node:path");
    const mod = (await import(pathToFileURL(resolve(localScorePath)).href)) as { default: unknown };
    choreo = mod.default;
  }

  if (!choreo) {
    ui.warn(
      "No local source available — daemon cannot process runs without the choreography. Save source first.",
    );
    ui.dim("Re-run: swati join <choreoId> --role <role> (source will be downloaded)");
    return;
  }

  trigger.listen({
    choreoId: choreoId as `0x${string}`,
    role: opts.role,
    choreo: choreo as never,
    runtime,
    identityFile: identityFilePath,
    walletPrivateKey: opts.walletKey,
    reportResults: !!opts.walletKey,
  });

  await new Promise<void>((_, reject) => {
    process.on("SIGINT", () => {
      trigger.stop();
      process.exit(0);
    });
    process.on("SIGTERM", () => {
      trigger.stop();
      process.exit(0);
    });
    process.on("uncaughtException", reject);
  });
}

function toNetwork(n?: string): "mainnet" | "sepolia" | number {
  if (n === "mainnet") return "mainnet";
  if (n === "0g-testnet" || n === "16602") return 16602;
  return "sepolia";
}

async function fetchText(uri: string): Promise<string> {
  if (uri.startsWith("http://") || uri.startsWith("https://")) {
    const res = await fetch(uri);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.text();
  }
  if (uri.startsWith("ipfs://")) {
    const gateway = process.env["IPFS_GATEWAY"] ?? "https://ipfs.io";
    const res = await fetch(`${gateway}/ipfs/${uri.slice(7)}`);
    if (!res.ok) throw new Error(`IPFS ${res.status}`);
    return res.text();
  }
  throw new Error(`Unsupported URI: ${uri}`);
}

function buildDefaultConfig(axlEndpoint: string, _opts: JoinOptions) {
  const storageDir = pathJoin(homedir(), ".swati", "storage");
  return {
    transport: null as never,
    resolver: null as never,
    storage: new LocalFileStorage(storageDir),
    gates: { local: new LocalGate({ timeoutMs: 30_000, retries: 1 }) },
    llm: null as never,
    choreographies: {},
    axlEndpoint,
  };
}
